### ISSUE TITLE
Can not build for windows

### ISSUE THREAD

**Issue by Eugene9999** [pornel/giflossy#4]
Hi
Can not build sources with Makefile.w32

https://github.com/pornel/giflossy

gifwrite.c
..\include\lcdf/inttypes.h(25) : warning C4142: benign redefinition of type
gifwrite.c(202) : error C2143: syntax error : missing ';' before 'type'
gifwrite.c(206) : error C2143: syntax error : missing ';' before 'type'
gifwrite.c(211) : error C2065: 'dith' : undeclared identifier
gifwrite.c(211) : error C2065: 'undith' : undeclared identifier
gifwrite.c(215) : error C2061: syntax error : identifier 'diffused_difference'
gifwrite.c(215) : error C2059: syntax error : ';'
gifwrite.c(215) : error C2059: syntax error : 'type'
gifwrite.c(320) : error C2275: 'uint8_t' : illegal use of this type as an expres
sion
        ..\include\lcdf/inttypes.h(16) : see declaration of 'uint8_t'
gifwrite.c(320) : error C2146: syntax error : missing ';' before identifier 'suf
fix'
gifwrite.c(320) : error C2065: 'suffix' : undeclared identifier
gifwrite.c(322) : error C2065: 'suffix' : undeclared identifier
gifwrite.c(325) : error C2065: 'suffix' : undeclared identifier
gifwrite.c(325) : error C2059: syntax error : '{'
gifwrite.c(333) : error C2065: 'suffix' : undeclared identifier
gifwrite.c(338) : error C2065: 'suffix' : undeclared identifier
gifwrite.c(363) : warning C4013: 'diffused_difference' undefined; assuming exter
n returning int
gifwrite.c(363) : error C2440: 'initializing' : cannot convert from 'int' to 'gf
c_rgbdiff'
gifwrite.c(430) : error C2275: 'Gif_Colormap' : illegal use of this type as an e
xpression
        ..\include\lcdfgif/gif.h(28) : see declaration of 'Gif_Colormap'
gifwrite.c(430) : error C2065: 'gfcm' : undeclared identifier
gifwrite.c(435) : error C2065: 'gfcm' : undeclared identifier
gifwrite.c(435) : warning C4047: '=' : 'int' differs in levels of indirection fr
om 'Gif_Colormap *'
gifwrite.c(495) : error C2065: 'gfcm' : undeclared identifier
gifwrite.c(495) : warning C4047: 'function' : 'const Gif_Colormap *' differs in
levels of indirection from 'int'
gifwrite.c(495) : warning C4024: 'gfc_lookup_lossy' : different types for formal
 and actual parameter 2
gifwrite.c(495) : error C2059: syntax error : '{'
gifwrite.c(906) : warning C4244: 'function' : conversion from 'uint16_t' to 'uin
t8_t', possible loss of data
gifwrite.c(1040) : warning C4244: 'function' : conversion from 'long' to 'uint16
_t', possible loss of data
gifwrite.c(1124) : error C2275: 'Gif_CodeTable' : illegal use of this type as an
 expression
        gifwrite.c(70) : see declaration of 'Gif_CodeTable'
gifwrite.c(1124) : error C2146: syntax error : missing ';' before identifier 'gf
c'
gifwrite.c(1124) : error C2065: 'gfc' : undeclared identifier
gifwrite.c(1125) : error C2065: 'gfc' : undeclared identifier
gifwrite.c(1125) : warning C4133: 'function' : incompatible types - from 'int *'
 to 'Gif_CodeTable *'
gifwrite.c(1132) : error C2143: syntax error : missing ';' before 'type'
gifwrite.c(1134) : error C2065: 'gfc' : undeclared identifier
gifwrite.c(1134) : warning C4133: 'function' : incompatible types - from 'int *'
 to 'Gif_CodeTable *'
gifwrite.c(1135) : error C2065: 'ok' : undeclared identifier
gifwrite.c(1147) : error C2275: 'Gif_Writer' : illegal use of this type as an ex
pression
        ..\include\lcdfgif/gif.h(251) : see declaration of 'Gif_Writer'
gifwrite.c(1147) : error C2065: 'grr' : undeclared identifier
gifwrite.c(1148) : error C2065: 'grr' : undeclared identifier
gifwrite.c(1151) : error C2143: syntax error : missing ';' before 'type'
gifwrite.c(1152) : error C2143: syntax error : missing ';' before 'type'
gifwrite.c(1153) : error C2065: 'i' : undeclared identifier
gifwrite.c(1154) : error C2065: 'ok' : undeclared identifier
gifwrite.c(1154) : error C2065: 'grr' : undeclared identifier
gifwrite.c(1154) : warning C4047: 'function' : 'Gif_Writer *' differs in levels
of indirection from 'int'
gifwrite.c(1154) : warning C4024: 'write_gif_write_image_and_extensions' : diffe
rent types for formal and actual parameter 2
gifwrite.c(1154) : error C2065: 'i' : undeclared identifier
gifwrite.c(1155) : error C2065: 'ok' : undeclared identifier
gifwrite.c(1159) : error C2065: 'grr' : undeclared identifier
gifwrite.c(1159) : warning C4047: 'function' : 'Gif_Writer *' differs in levels
of indirection from 'int'
gifwrite.c(1159) : warning C4024: 'Gif_WriteEnd' : different types for formal an
d actual parameter 2
gifwrite.c(1161) : error C2065: 'ok' : undeclared identifier
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 11.0
\VC\BIN\cl.EXE"' : return code '0x2'
Stop.

C:\Users\Eugene\Desktop\ConvertionTest\giflossy-master\src>
-------- Завершение пересылаемого сообщения --------

**Comment by pornel** [comment]
I'm not sure if MSVC is going to work — it has very out-of-date C compiler. Try GCC (MinGW).

**Comment by Eugene9999** [comment]
Thanx for the direction.
How I did.
OS - Windows 8.1
!) install http://www.mingw.org/wiki/msys (I used MinGW Installation Manager);
2) Make sure register within Path environment variable;
3) In project folder run
aclocal
autoconf
automake --add-missing
4) If complains for missing config.h.in run autoreconf --install
5) ./configure
make 
make install
6) in src folder you will find applications
